version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=lighthouse
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=1234
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=1234
    volumes:
      - "influxdb-data:/var/lib/influxdb"
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    volumes:
      - "chronograf-data:/var/lib/chronograf"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=telegraf
      - INFLUXDB_PASSWORD=1234
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=1234"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  chronograf-data:
  grafana-data:
